# inventory.ini

[k3s_nodes]
k3s-node1 ansible_host=13.233.223.174 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
k3s-node2 ansible_host=13.201.43.198 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3
k3s-node3 ansible_host=3.108.221.202 ansible_user=ubuntu ansible_python_interpreter=/usr/bin/python3


[k3s_nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/prashant/Desktop/k3s/id_rsa